### ISSUE TITLE
Crash when boosting in an Automobility car into ice/water

### ISSUE THREAD

**Issue by Zorbiac** [Erik-s-Foxpack/cubeempireserver#1]
**Опишите ошибку**
Автомобиль из Automobility: 
- Automobile Frame (Wooden Motorcar)
- Automobile Wheel (Standard)
- Automobile Engine (Iron)

**Как воспроизвести:**
1. Жестко дрифтуешь (до 3 стадии) на холме на машине автомобилити
2. Отпускаешь дрифт и летишь в сторону воды на бусте
3. Произошла ошибка

**Файл краш-репорта**
Файл не сгенерирован, код завершения: 1

**Информация об устройстве:**
 - Версия ОС: Windows 11 22H2 22621.1555
 - Какой лаунчер: License

**Дополнительная информация**
Почти уверен что невоспроизводимо и просто рандомный краш :(

**Comment by SleeplessF0X** [comment]
Баг не воспроизводится, логов на сервере касательно ошибки нет, вероятно рандомный краш клиента, закрываем до повторения
