### ISSUE TITLE
Ошибка с вылетом после ударов по модовым мобам

### ISSUE THREAD

**Issue by NIKITANDER** [Erik-s-Foxpack/cubeempireserver#2]
**Опишите ошибку**
Перестал проходить дамаг по живнотным, а так-же они перестали двигатсья, вышел с сервера и крашнуло игру целиком

**Как воспроизвести**
Шаги к воспроизведению ошибки:
1. Пойти к 'животным'
2. Нажать на 'кнопку атаки'
3. Прыгнуть в 'из сервера'
4. Произошла ошибка

**Файл краш-репорта**
[latest.log](https://github.com/ForestF0X/cubeempireserver/files/11240436/latest.log)

**Информация об устройстве:**
 - Версия ОС: [Windows 11 22H2]
 - Какой лаунчер: [Pirate]

**Дополнительная информация**
Добавьте любую дополнительную информацию об ошибке сюда

**Comment by SleeplessF0X** [comment]
Возможно проблема в `bison_baby` из `alexsmobs`

**Comment by SleeplessF0X** [comment]
Вылет после проверок не повторился, наиболее вероятной проблемой были проблемы с интернетом на клиенте. Закрываю до повторения.
