### ISSUE TITLE
Crash when pondering the Enchanting Guide

### ISSUE THREAD

**Issue by Zorbiac** [Erik-s-Foxpack/cubeempireserver#3]
**Опишите ошибку**
Game crashed while pondering the Enchanting Guide (item from Create: Enchantment Industry)
![image](https://user-images.githubusercontent.com/130840784/233989705-92ccad9a-55de-4eb4-8222-9c72436c826b.png)

**Как воспроизвести**
Шаги к воспроизведению ошибки:
1. Find the Enchantment Guide in the JEI menu
2. Click to open the crafting recipe
3. Ponder by holding the assigned key
4. Crash happened when going from the first scene to the second one (scene switched via key bind)

**Файл краш-репорта**
[crash-2023-04-24_15.46.58-client.txt](https://github.com/ForestF0X/cubeempireserver/files/11310096/crash-2023-04-24_15.46.58-client.txt)

**Информация об устройстве**
 - Версия ОС: Windows 11 22H2
 - Какой лаунчер: License
 
**Дополнительная информация**
Exit code: -1

Launcher crash message:

> The game crashed whilst ticking screen
> Error: java.lang.ClassCastException: class com.simibubi.create.foundation.ponder.PonderWorld cannot be cast to class net.minecraft.world.level.chunk.ChunkAccess (com.simibubi.create.foundation.ponder.PonderWorld is in module create@0.5.0.i of loader 'TRANSFORMER' @5b8853; net.minecraft.world.level.chunk.ChunkAccess is in module minecraft@1.19.2 of loader 'TRANSFORMER' @5b8853)

**Comment by SleeplessF0X** [comment]
Didn't bother to check the logs when it happened, but I encountered same-ish error with one of Create mechanisms, I think it was Millstone
All the same steps, different mechanism
I'll check later and come back with more details, might need to investigate better and submit a report to Create

**Comment by SleeplessF0X** [comment]
So yes, pondering the Millstone crashes the game too. Seems like a report to Create developers if it wasn't reported yet, here is my crash-report and logs for future analysis
[crash-2023-04-25_00.33.10-client.txt](https://github.com/ForestF0X/cubeempireserver/files/11314042/crash-2023-04-25_00.33.10-client.txt)
[latest.log](https://github.com/ForestF0X/cubeempireserver/files/11314046/latest.log)

**Comment by Zorbiac** [comment]
Same crash while pondering about a Chute 

[crash-2023-04-25_17.54.11-client.txt](https://github.com/ForestF0X/cubeempireserver/files/11323222/crash-2023-04-25_17.54.11-client.txt)
[latest.log](https://github.com/ForestF0X/cubeempireserver/files/11323230/latest.log)

**Comment by Zorbiac** [comment]
The saga continues. Today's hero — brass tunnel.


[crash-2023-04-25_19.08.17-client.txt](https://github.com/ForestF0X/cubeempireserver/files/11323987/crash-2023-04-25_19.08.17-client.txt)

[latest.log](https://github.com/ForestF0X/cubeempireserver/files/11323984/latest.log)

**Comment by Zorbiac** [comment]
Some external sources and possible leads:

[Here](https://www.reddit.com/r/CreateMod/comments/11c34vc/crash_on_ponder_screen/
) on Reddit ObscureAPI is mentioned as the problem

Also found creators-of-create/create#4485, but it mentions Droplight/Item Physic which we do not have installed yet. 

However! On reddit the error message is different from what we have, but in the linked Git issue is the same.

Also there's Creators-of-Create/Create#4142, which has some more issues linked inside. My expertise is not enough to read through the logs, thus I must summon the mighty @ForestF0X

**Comment by SleeplessF0X** [comment]
My sleepless ass kinda found the solution
_in Heavy's voice_ no big surprise
So, looking at our logs by my sleepy-creepy eyes I found a very particular line
`at com.abdelaziz.canary.common.entity.CanaryEntityCollisions.getCollisionShapeBelowEntity(CanaryEntityCollisions.java:195) ~[canary-mc1.19.2-0.1.9.jar%23347!/:0.1.9] {re:mixin,re:classloading}
`
As Canary is an unofficial Lithium port for Forge, and as I had troubles with it before (and I had no questions when throwing it into mods folder again lmao) I can most definetely say that demolishing it to atoms/changing to other port of Lithium is the solution. I'll check both variants tomorrow and come back with results

Also, good job on the research!

**Comment by SleeplessF0X** [comment]
Good news: Canary had been updated recently, and just look at what I found in changelog
![image](https://user-images.githubusercontent.com/37906556/234476872-846de071-5b50-4e37-b429-e5bb81780d81.png)
I'll check it out later today

**Comment by SleeplessF0X** [comment]
Upgrading Canary to newest version fixed all the issues. I'll include it in the next mods update (will be out maybe even today)
