### ISSUE TITLE
Minecraft Kaboom

### ISSUE THREAD

**Issue by Hosakooo** [Erik-s-Foxpack/cubeempireserver#4]
**Опишите ошибку**
При стрельбе из минигана происходит краш миникрафта

**Как воспроизвести**
Шаги к воспроизведению ошибки:
1. Взять 8 barrel Minigun
2. Начать неистово стрелять из него
3. Произошел отвал миникрафта
4. Стрельба велась в воздух

Шейдеры: Complimentary  Remagined
**Файл краш-репорта**
Приложите самый новый файл crash-report из папки игры

**Информация об устройстве:**
 - Версия ОС: [ Windows 10 21H2]
[crash-2023-04-24_15.15.55-client.txt](https://github.com/ForestF0X/cubeempireserver/files/11310523/crash-2023-04-24_15.15.55-client.txt)

[crash-2023-04-24_15.15.55-client.txt](https://github.com/ForestF0X/cubeempireserver/files/11310515/crash-2023-04-24_15.15.55-client.txt)

 - Какой лаунчер: [Pirate]

**Дополнительная информация**
Добавьте любую дополнительную информацию об ошибке сюда
Code: 0 ( пациент мертв )
[crash-2023-04-24_15.15.55-client.txt](https://github.com/ForestF0X/cubeempireserver/files/11310499/crash-2023-04-24_15.15.55-client.txt)

**Comment by SleeplessF0X** [comment]
Нужны уточнения:
1. Какой из двух миниганов мода крашнул игру?
2. Стрельба велась в воздух или в какой-то блок/какие-то блоки? Если в блок/блоки, то просьба уточнить в какой/какие

Совет на будущее: Проверяй как будет выглядеть репорт на вкладке превью, у тебя затроился по всему репорту краш-репорт игры
