### ISSUE TITLE
Crash MOBYDICK

### ISSUE THREAD

**Issue by ARHONTER** [Erik-s-Foxpack/cubeempireserver#5]
**Опишите ошибку**
Кубач вылетел после убийства кашалота

**Как воспроизвести**
Стреляеш в кашалота из лука
а
он умирает
а
прыгаеш в воду за лутом
а
краш кубов
а 
улетаеш на пердаке в стратасферу

**Файл краш-репорта**
Приложите самый новый файл crash-report из папки игры
[hs_err_pid13832.log](https://github.com/ForestF0X/cubeempireserver/files/11314032/hs_err_pid13832.log)

**Информация об устройстве:**
 - Версия ОС:  Windows 11 22H2
 - Какой лаунчер: Pirate

**Дополнительная информация**
я убил кашалота

**Comment by SleeplessF0X** [comment]
*dear_god_tf2.gif*

**Comment by ARHONTER** [comment]
[2023-04-24-1.log.gz](https://github.com/ForestF0X/cubeempireserver/files/11314147/2023-04-24-1.log.gz)

**Comment by SleeplessF0X** [comment]
В логах майна ничего нет, если системный лог всплыл именно после краша - то судя по всему была какая-то ошибка с оперативкой, к сожалению не моя специальность и я такое особо не разбирал никогда - но могу предположить какую-то утечку памяти или некорректное поведение майна (в логах идёт информация об ошибке работы именно JRE, то есть это _вроде_ не ошибка винды). Утечка памяти точно от меня не зависит, а вот поведение майна зависит потому что у нас две тонны модов установлено.

Идём дальше - в логах есть инфа по какойто работе Journey Map в момент ошибки, то есть скорее всего - что-то попыталось прописаться не туда куда должно (я не очень опытный программист, еще и не по майну поэтому хз как еще описать мое предположение), если попытаться построить логическую цепочку из того что понимаю я - Journey Map попыталась чето отрендерить у себя, у нее случилась какая-то ошибка, JRE поймал EXCEPTION_ACCESS_VIOLATION и упал как Барецкий. Если конечно лог касательно JRE всплыл именно после этого краша.

Скорее всего ошибку придется закрыть как невоспроизводимую, но я еще не проверял истребление популяции кашалотов, так что пока думаем дальше

**Comment by SleeplessF0X** [comment]
Пришёл к решению что это было локальной ошибкой системы либо невоспроизводимым локальной ошибкой игры. Закрываю до повторения
