### ISSUE TITLE
Biomes' O Plenty doors not working correctly

### ISSUE THREAD

**Issue by Hosakooo** [Erik-s-Foxpack/cubeempireserver#6]
Двери из мода Biome's o Plenty некорректно работают, а именно магическая дверь.

Шаги к воспроизведению ошибки:
1. Ставите дверь, пытаетесь её открыть, она открывается, но коллизия закрытой двери не пропадает
2. Если вставать на нажимные плиты, то дверь также не открывается

Видео с демонстрацией бага: https://www.youtube.com/watch?v=t90PXUDS-9g

Лог файл представится позже

**Информация об устройстве:**
 - Версия ОС: [ Windows 10 21H2]
 - Какой лаунчер: [Pirate]

**Дополнительная информация**
Возможно все двери из этого мода также не работают как надо

**Comment by SleeplessF0X** [comment]
Проблема в моде Double Doors, будет или удалён или заменён в ближашем обновлении модов

**Comment by SleeplessF0X** [comment]
Проблема повторилась на сервере, проблема не в моде а в взаимодействии нажимных плит с дверями из модов. Буду разбираться дальше.

**Comment by SleeplessF0X** [comment]
Проблема не просто во взаимодействии плит с дверьми, а в рассинхроне клиента с сервером. На текущий момент нерешаемо, если найду способ исправить - оповещу в обновлении сервера
