### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by ARHONTER** [Erik-s-Foxpack/cubeempireserver#8]
Crash at launch

After installing modpack v.4.1.0, i've tried to launch cubes few times, however tlauncher crashed at any attempt of mine.

Logs:
[tl-logger10072629312376727085.txt](https://github.com/ForestF0X/cubeempireserver/files/11856445/tl-logger10072629312376727085.txt)

 - ОС Windows 11 22H2]
 -  Pirate launcher

**Comment by ARHONTER** [comment]
[crash-2023-04-27_21.43.54-server.txt](https://github.com/ForestF0X/cubeempireserver/files/11857930/crash-2023-04-27_21.43.54-server.txt)
Crashed after hotfix

**Comment by SleeplessF0X** [comment]
Was a local issue, closed after resolving
